server:
  port: 8080
  contextPath: /micropay
---
spring:
  profiles:
    development
logging:
  level:
    br.com.micropay: DEBUG
    org.springframework: INFO
    root: INFO
  file: /tmp/micropay.log
